name = "manuel"
license = "MIT"
licenselink = "https://github.com/riccardomc/manuel-hugo-theme/blob/master/LICENSE"
description = "A hugo theme, under a quiet sky"
homepage = "https://github.com/riccardomc/manuel-hugo-theme"
tags = ["blog", "simple", "clean", "highlight", "readable"]
features = ["blog", "simple", "clean", "highlight"]
min_version = "0.51"

[author]
  name = "Riccardo M. Cefala"
  homepage = "https://riccardo.cefala.net/"
  repo = "https://github.com/riccardomc/manuel-hugo-theme"

[original-author]
  name = "Rainer Chiang"
  homepage = "https://rainerchiang.github.io/"
  repo = "https://github.com/RainerChiang/simpleness"
